# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# OUTPUTS
# These outputs are used to pass information to other modules
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# ---------------------------------------------------------------------------------------------------------------------
# DEPLOYMENT OUTPUTS
# Information about the deployed models
# ---------------------------------------------------------------------------------------------------------------------

output "deployments" {
  description = "Map of deployed AI models and their metadata"
  value = var.enabled ? {
    for k, v in azurerm_cognitive_deployment.deployments : k => {
      id                         = v.id
      name                       = v.name
      cognitive_account_id       = v.cognitive_account_id
      model_format               = v.model[0].format
      model_name                 = v.model[0].name
      model_version              = v.model[0].version
      scale_type                 = v.scale[0].type
      scale_capacity             = v.scale[0].capacity
      scale_tier                 = v.scale[0].tier
      scale_size                 = v.scale[0].size
      scale_family               = v.scale[0].family
      rai_policy_name            = v.rai_policy_name
      version_upgrade_option     = v.version_upgrade_option
      dynamic_throttling_enabled = v.dynamic_throttling_enabled
    }
  } : {}
}

output "deployment_ids" {
  description = "Map of deployment names to their IDs"
  value = var.enabled ? {
    for k, v in azurerm_cognitive_deployment.deployments : k => v.id
  } : {}
}

output "deployment_names" {
  description = "List of all deployment names"
  value       = var.enabled ? keys(azurerm_cognitive_deployment.deployments) : []
}

output "deployment_endpoints" {
  description = "Map of deployment names to their endpoints (base cognitive account endpoint)"
  value = var.enabled ? {
    for k, v in azurerm_cognitive_deployment.deployments : k => v.cognitive_account_id
  } : {}
}

# ---------------------------------------------------------------------------------------------------------------------
# LABEL MODULE OUTPUTS
# These outputs are used for consistent tagging and naming
# ---------------------------------------------------------------------------------------------------------------------

output "tags" {
  description = "The tags to apply to resources"
  value       = module.label.tags
}

output "context" {
  description = "Exported context for use by other modules"
  value       = module.label.context
}

output "id" {
  description = "Disambiguated ID generated by the label module"
  value       = module.label.id
}

output "enabled" {
  description = "Whether this module is enabled"
  value       = var.enabled
}
