components:
  terraform:
    azure-postgres-database:
      vars:
        stage: "dev"

        # Development SKU - Burstable for cost optimization
        sku_name: "B_Standard_B1ms"
        storage_mb: 32768
        postgres_version: "16"

        # Lower retention for development
        backup_retention_days: 7
        geo_redundant_backup_enabled: false

        # No high availability in dev
        high_availability_enabled: false

        # Allow public access for development (can be restricted per stack)
        public_network_access_enabled: true

        # Development database configuration
        databases:
          devdb:
            collation: "en_US.utf8"
            charset: "UTF8"

        # Basic server configurations for development
        server_configurations:
          max_connections: "100"

        tags:
          Environment: "Development"
          CostCenter: "Engineering"
          AutoShutdown: "true"
