components:
  terraform:
    azure-postgres-database:
      vars:
        stage: "prod"

        # Production SKU - General Purpose with more capacity
        sku_name: "GP_Standard_D4s_v3"
        storage_mb: 131072
        postgres_version: "16"
        zone: "1"

        # Extended retention for production
        backup_retention_days: 35
        geo_redundant_backup_enabled: true

        # High availability enabled with zone redundancy
        high_availability_enabled: true
        high_availability_mode: "ZoneRedundant"
        standby_availability_zone: "2"

        # Restricted network access for production
        public_network_access_enabled: false

        # Production database configuration
        databases:
          proddb:
            collation: "en_US.utf8"
            charset: "UTF8"

        # Optimized server configurations for production
        server_configurations:
          max_connections: "200"
          shared_buffers: "256MB"
          effective_cache_size: "1GB"
          work_mem: "4MB"
          maintenance_work_mem: "64MB"

        # Maintenance window - Sunday 2 AM
        maintenance_window:
          day_of_week: 0
          start_hour: 2
          start_minute: 0

        tags:
          Environment: "Production"
          CostCenter: "Operations"
          Criticality: "High"
          BackupPolicy: "Daily"
