components:
  terraform:
    azure-datafactory:
      vars:
        # Production environment settings
        public_network_enabled: false
        managed_virtual_network_enabled: true

        tags:
          Environment: "Production"
          CostCenter: "Operations"
          Criticality: "High"
          BackupPolicy: "Daily"
