variable "enabled" {
  description = "Set to false to prevent the module from creating any resources"
  type        = bool
  default     = true
}

variable "location" {
  description = "The Azure Region where the Azure Language Services should be created"
  type        = string
}

variable "resource_group_name" {
  description = "The name of the resource group in which to create the Azure Language Services"
  type        = string
}

# Azure Language Services Configuration
variable "sku_name" {
  description = "The SKU name for the Azure Language Services. Possible values are F0 (Free), S (Standard)"
  type        = string
  default     = "S"
  validation {
    condition     = contains(["F0", "S"], var.sku_name)
    error_message = "The sku_name must be F0 or S for Azure Language Services."
  }
}

variable "custom_subdomain_name" {
  description = "The custom subdomain name for the Azure Language Services. If not provided, it will use the generated label ID"
  type        = string
  default     = null
}

variable "public_network_access_enabled" {
  description = "Whether public network access is allowed for the Azure Language Services"
  type        = bool
  default     = false
}

# Network Access Control
variable "network_acls" {
  description = "Network rules restricting access to the Azure Language Services"
  type = object({
    default_action                       = string
    ip_rules                             = optional(set(string))
    subnet_id                            = optional(string)
    ignore_missing_vnet_service_endpoint = optional(bool, false)
  })
  default = null
}

# Managed Identity
variable "identity_type" {
  description = "The type of Managed Identity which should be assigned to the Azure Language Services. Possible values are SystemAssigned, UserAssigned and SystemAssigned, UserAssigned"
  type        = string
  default     = null
  validation {
    condition     = var.identity_type == null || contains(["SystemAssigned", "UserAssigned", "SystemAssigned, UserAssigned"], var.identity_type)
    error_message = "The identity_type must be either SystemAssigned, UserAssigned, or SystemAssigned, UserAssigned."
  }
}

variable "identity_ids" {
  description = "A list of User Assigned Managed Identity IDs to be assigned to this Azure Language Services. Required when identity_type is UserAssigned or SystemAssigned, UserAssigned"
  type        = list(string)
  default     = null
}

# Label module variables
variable "namespace" {
  description = "ID element. Usually an abbreviation of your organization name, e.g. 'eg' or 'cp', to help ensure generated IDs are globally unique"
  type        = string
  default     = null
}

variable "tenant" {
  description = "ID element _(Rarely used, not included by default)_. A customer identifier, indicating who this instance of a resource is for"
  type        = string
  default     = null
}

variable "environment" {
  description = "ID element. Usually used for region e.g. 'uw2', 'us-west-2', OR role 'prod', 'staging', 'dev', 'UAT'"
  type        = string
  default     = null
}

variable "stage" {
  description = "ID element. Usually used to indicate role, e.g. 'prod', 'staging', 'source', 'build', 'test', 'deploy', 'release'"
  type        = string
  default     = null
}

variable "name" {
  description = "ID element. Usually the component or solution name, e.g. 'app' or 'jenkins'"
  type        = string
  default     = null
}

variable "attributes" {
  description = "ID element. Additional attributes (e.g. `workers` or `cluster`) to add to `id` in the order they appear in the list"
  type        = list(string)
  default     = []
}

variable "delimiter" {
  description = "Delimiter to be used between ID elements"
  type        = string
  default     = "-"
}

variable "tags" {
  description = "Additional tags (e.g. `{'BusinessUnit': 'XYZ'}`)"
  type        = map(string)
  default     = {}
}

variable "regex_replace_chars" {
  description = "Terraform regular expression (regex) string. Characters matching the regex will be removed from the ID elements"
  type        = string
  default     = null
}

variable "label_order" {
  description = "The order in which the labels (ID elements) appear in the id"
  type        = list(string)
  default     = null
}

variable "label_key_case" {
  description = "Controls the letter case of the tags keys (label names) for tags generated by this module"
  type        = string
  default     = null
}

variable "label_value_case" {
  description = "Controls the letter case of the tags values for tags generated by this module"
  type        = string
  default     = null
}

variable "id_length_limit" {
  description = "Limit `id` to this many characters (minimum 6)"
  type        = number
  default     = null
}
