# stacks/catalog/azure-apim/mixins/dev.yaml

components:
  terraform:
    azure-apim:
      vars:
        # Development environment settings - Developer tier
        sku_name: "Developer"
        capacity: 1

        # Network access - more permissive for development
        virtual_network_type: "None"
        public_network_access_enabled: true

        # Security Settings - Enforce secure protocols even in dev
        security:
          enable_backend_ssl30: false
          enable_backend_tls10: false
          enable_backend_tls11: false
          enable_frontend_ssl30: false
          enable_frontend_tls10: false
          enable_frontend_tls11: false
          triple_des_ciphers_enabled: false

        # Developer Portal - Enable for development and testing
        sign_in:
          enabled: true

        sign_up:
          enabled: true
          terms_of_service:
            consent_required: false
            enabled: true
            text: "Development environment - Accept terms to continue"

        # Client certificates not required in dev
        client_certificate_enabled: false

        # Private endpoints for secure development access
        create_private_endpoint: false
