# stacks/catalog/azure-apim/mixins/prod.yaml

components:
  terraform:
    azure-apim:
      vars:
        # Production environment settings - Premium tier with HA
        sku_name: "Premium"
        capacity: 2

        # High Availability - Deploy across availability zones
        zones:
          - "1"
          - "2"
          - "3"

        # Network Configuration - Internal VNet for security
        virtual_network_type: "Internal"
        public_network_access_enabled: false

        # Security Settings - Maximum security for production
        client_certificate_enabled: true

        security:
          enable_backend_ssl30: false
          enable_backend_tls10: false
          enable_backend_tls11: false
          enable_frontend_ssl30: false
          enable_frontend_tls10: false
          enable_frontend_tls11: false
          tls_ecdhe_ecdsa_with_aes128_cbc_sha_ciphers_enabled: false
          tls_ecdhe_ecdsa_with_aes256_cbc_sha_ciphers_enabled: false
          tls_ecdhe_rsa_with_aes128_cbc_sha_ciphers_enabled: false
          tls_ecdhe_rsa_with_aes256_cbc_sha_ciphers_enabled: false
          tls_rsa_with_aes128_cbc_sha256_ciphers_enabled: false
          tls_rsa_with_aes128_cbc_sha_ciphers_enabled: false
          tls_rsa_with_aes256_cbc_sha256_ciphers_enabled: false
          tls_rsa_with_aes256_cbc_sha_ciphers_enabled: false
          triple_des_ciphers_enabled: false

        # Protocol Settings
        protocols:
          enable_http2: true

        # Developer Portal Settings - Production configuration
        sign_in:
          enabled: true

        sign_up:
          enabled: true
          terms_of_service:
            consent_required: true
            enabled: true
            text: "Please accept our terms of service to access the API portal."

        # Managed Identity for secure Azure resource access
        identity_type: "SystemAssigned"

        # Private endpoints mandatory for production
        create_private_endpoint: true

        # Additional locations for multi-region deployment (optional)
        # Uncomment and configure based on requirements
        # additional_locations:
        #   - location: "westus2"
        #     capacity: 2
        #     zones:
        #       - "1"
        #       - "2"
        #       - "3"
