variable "enabled" {
  type        = bool
  description = "Set to false to prevent the module from creating any resources"
  default     = true
}

# Label module variables
variable "namespace" {
  type        = string
  description = "Namespace, which could be your organization name or abbreviation, e.g. 'eg' or 'cp'"
  default     = null
}

variable "tenant" {
  type        = string
  description = "ID element _(Rarely used, not included by default)_. A customer identifier, indicating who this instance of a resource is for"
  default     = null
}

variable "environment" {
  type        = string
  description = "ID element. Usually used for region e.g. 'uw2', 'us-west-2', OR role 'prod', 'staging', 'dev', 'UAT'"
  default     = null
}

variable "stage" {
  type        = string
  description = "ID element. Usually used to indicate role, e.g. 'prod', 'staging', 'source', 'build', 'test', 'deploy', 'release'"
  default     = null
}

variable "name" {
  type        = string
  description = "ID element. Usually the component or solution name, e.g. 'app' or 'jenkins'."
  default     = null
}

variable "attributes" {
  type        = list(string)
  description = "ID element. Additional attributes (e.g. `1`)"
  default     = []
}

variable "delimiter" {
  type        = string
  description = "Delimiter to be used between ID elements. Defaults to `-` (hyphen). Set to `\"\"` to use no delimiter at all."
  default     = null
}

variable "tags" {
  type        = map(string)
  description = "Additional tags (e.g. `{'BusinessUnit': 'XYZ'}`)."
  default     = {}
}

variable "regex_replace_chars" {
  type        = string
  description = "Terraform regular expression (regex) string. Characters matching the regex will be removed from the ID elements."
  default     = null
}

variable "label_order" {
  type        = list(string)
  description = "The order in which the labels (ID elements) appear in the `id`. Defaults to [\"namespace\", \"environment\", \"stage\", \"name\", \"attributes\"]."
  default     = null
}

variable "label_key_case" {
  type        = string
  description = "Controls the letter case of the `tags` keys (label names) for tags generated by this module."
  default     = null
}

variable "label_value_case" {
  type        = string
  description = "Controls the letter case of ID elements (labels) as included in `id`, set as tag values, and output by this module individually."
  default     = null
}

variable "id_length_limit" {
  type        = number
  description = "Limit `id` to this many characters (minimum 6). Set to `0` for unlimited length."
  default     = null
}

# Azure Application Security Group specific variables
variable "location" {
  type        = string
  description = "The Azure Region where the Application Security Group should exist"
}

variable "resource_group_name" {
  type        = string
  description = "The name of the Resource Group in which the Application Security Group should exist"
}

variable "asg_name" {
  type        = string
  description = "The name of the Application Security Group. If not provided, the name will be generated using the label module"
  default     = null
}
