components:
  terraform:
    azure-frontdoor:
      vars:
        stage: "dev"

        # Development uses Standard SKU for cost savings
        sku_name: "Standard_AzureFrontDoor"

        # Shorter timeout for development
        response_timeout_seconds: 60

        # Development-specific origin groups
        origin_groups:
          default:
            name: "dev-origin-group"
            session_affinity_enabled: false
            load_balancing:
              sample_size: 2
              successful_samples_required: 1
              additional_latency_in_milliseconds: 50
            health_probe:
              protocol: "Https"
              interval_in_seconds: 120
              request_type: "HEAD"
              path: "/health"
